### ISSUE TITLE
Question: Are where any advantage to cache .choosenim ?

### ISSUE THREAD

**Issue by inv2004** [jiro4989/setup-nim-action#18]
Hello,

Thank you for your package, I added it to https://github.com/nim-lang/Nim/wiki/BuildServices , because I suppose it is the easiest way to setup github actions for nim.

But I have a question:
In "Use cache" example I see caching for ~/.choosenim, but in the source file I see it downloads choosenim every installation. Are there any reasons to use this cache in the case?

It is clear why cache .nimble.

Thank you,

**Comment by jiro4989** [comment]
>In "Use cache" example I see caching for ~/.choosenim, but in the source file I see it downloads choosenim every installation. Are there any reasons to use this cache in the case?

The reason is speed-up for `devel` version of Nim.
[This build-job](https://github.com/jiro4989/setup-nim-action/runs/727341897) uses only 1 sec.

The build of `devel` or `devel --latest`  needs much time.
Choosenim switches vesion of compiler if `~/.choosenim` has existed.
(But this means `devel` is not always really latest ...)

The CI probably does not need caching `~/.choosenim` If you will not use `devel` compiler.

**Comment by jiro4989** [comment]
I removed `~/.choosenim` cache from `basic usage`.

And I added a new example for `devel --latest`.
https://github.com/jiro4989/setup-nim-action#devel---latest-usage

This example needs a caching `~/.choosenim` for speed-up.

Thank your question.

**Comment by inv2004** [comment]
Do I understand correct that it runs choosenim every run anyway?

Are there any way to compare Nim version from .nimble with nim-version
value and run installation if it is not equal only? Or something like that.

**Comment by jiro4989** [comment]
> Do I understand correct that it runs choosenim every run anyway?

I think that is not correct.
But it effects only a few minute of CI workflow.
I don't care.

> Are there any way to compare Nim version from .nimble with nim-version
value and run installation if it is not equal only?

No. `setup-nim-action` does not have the function like it.

**Comment by inv2004** [comment]
Thank you for your answers. I was thinking how to reduce build time as much as possible for stable nim
