### ISSUE TITLE
Action fails on windows

### ISSUE THREAD

**Issue by kdheepak** [jiro4989/setup-nim-action#21]
I get the following error when I try to setup nim on Windows.

```
> Run jiro4989/setup-nim-action@v1
choosenim-init: Downloading choosenim-0.6.0_windows_amd64.zip
Archive:  /tmp/choosenim-0.6.0_windows_amd64.zip
  inflating: /tmp/choosenim/choosenim.exe  
  inflating: /tmp/choosenim/libeay64.dll  
  inflating: /tmp/choosenim/ssleay64.dll  
  inflating: /tmp/choosenim/runme.bat  
Downloading DLLs (openssl, pcre, ...)

[                                                  ] 0.06047% 4kb/s
[##################################################] 100.0% 0kb/s
 Extracting dlls.zip
Downloading Nim 1.2.0 from nim-lang.org

[                                                  ] 0.01945% 4kb/s
[##################################################] 100.0% 0kb/s
 Extracting nim-1.2.0_x64.zip
   Building Nim 1.2.0
  Compiler: Already built
     Tools: Already built
  Installed component 'nim'
  Installed component 'nimble'
  Installed component 'nimgrep'
  Installed component 'nimpretty'
  Installed component 'nimsuggest'
  Installed component 'testament'
      Hint: Use 'choosenim <version/channel> --firstInstall' to add
        ... C:\Users\runneradmin\.nimble\bin to your PATH.
   Switched to Nim 1.2.0
    Prompt: C:\Users\runneradmin\.nimble\bin is not in your PATH environment variable.
        ...             Should it be added permanently? -> [forced yes]
      Note: PATH changes will only take effect in new sessions.
choosenim-init: ChooseNim installed in C:\Users\runneradmin\.nimble\bin
choosenim-init: You must now ensure that the Nimble bin dir is in your PATH.

d:\a\_actions\jiro4989\setup-nim-action\v1\lib\installer.js:81
                    throw err;
                    ^

Error: Command failed: choosenim 1.2.0

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'choosenim 1.2.0'
}
##[error]Error: Command failed: choosenim 1.2.0

```

Any suggestions on what to do to fix this?

**Comment by jiro4989** [comment]
@kdheepak 
I think that may be a problem of `choosenim` .
`setup-nim-action` just uses `choosenim`.
Please report to `choosenim` too.

https://github.com/dom96/choosenim/issues

**Comment by jiro4989** [comment]
Example, my windows-pc occured this error.

```bash
$ ~/.nimble/bin/choosenim.exe 1.2.0
      Info: C:\Users\jiro4989\.choosenim\downloads\dlls.zip already downloaded
 Extracting dlls.zip
     Error: Unable to extract. Error was '既に存在するファイルを作成することはできません。
        ... '.
```

**Comment by kdheepak** [comment]
I think you are right! I tried with an older commit where it definitely worked in the past and now it throws an error for Windows.

**Comment by jiro4989** [comment]
@kdheepak I added temporarily patch (but so dirty...) .
https://github.com/jiro4989/setup-nim-action/pull/22/files
`choosenim $version` fails on only windows.

Please re-check your workflow.

**Comment by kdheepak** [comment]
Thanks for making this change! This now works as expected on Windows!

In this patch, are you just running `sh init.sh -y` _twice_ instead of _once_ on Windows? Why does that change anything? I don't understand why this patch works but it works :)

**Comment by jiro4989** [comment]
> In this patch, are you just running sh init.sh -y twice instead of once on Windows?

No, this patch runs `sh init.sh -y` once.
https://github.com/jiro4989/setup-nim-action/pull/22/files#diff-49f374184f7542706ae947de9d44718eR82
This patch returns early and doesn't run `choosenim <version>`.

I found that `choosenim <version>` fails on Windows.
So I changed that `setup-nim-action` skips `choosenim <version>` on Windows.

But I could not found the reason that `choosenim <version>` fails on Windows.
I will watch https://github.com/dom96/choosenim/issues/204.

**Comment by kdheepak** [comment]
Got it! Thanks! I'll let you decide if you want to keep this issue open or not.

**Comment by Pebaz** [comment]
Unfortunately, this is still failing for me:

* https://github.com/Pebaz/nimporter/actions
* https://github.com/Pebaz/nimporter/actions/runs/135233177

**Comment by juancarlospaco** [comment]
If you delete the contents of the folder `C:\Users\user\.choosenim\downloads\` then it may work,  ...or not (?),
I tried reporting the Bug and it seems that is Fixed, but is not released, 
so for Windows you may need to build `choosenim` from sources of master, until next release of choosenim.

The action still failing on Windows as of today.

**Comment by jiro4989** [comment]
@juancarlospaco Caching the choosenim directory was the problem.

Fail in installing Nim when caching choosenim directory on Windows Vm.

Please try remove caching choosenim directory if you cache that.
