### ISSUE TITLE
Is the build failing a red herring?

### ISSUE THREAD

**Issue by iffy** [jiro4989/setup-nim-action#3]
I found this in the marketplace, but immediately dismissed it because the build badge said failing, and I (incorrectly) assumed that it only worked on Linux.  I made my own, but don't want to duplicate effort.  Is the badge a lie?

**Comment by jiro4989** [comment]
@iffy 

I think that `setup-nim-actions` works on Linux or Windows, but not working on macOS.

GitHub Actions had failed to test on macOS.
This is a problem of `choosenim`, is not a problem of `setup-nim-action`.
https://github.com/dom96/choosenim/issues/122

`setup-nim-actions` uses internally `choosenim`.
This problem will be solved when a problem of `choosenim` will be solved.

Thank you.

**Comment by iffy** [comment]
Hmm... mine works on macOS using choosenim: https://github.com/iffy/install-nim

**Comment by jiro4989** [comment]
Thank you.
A problem is here.
https://github.com/jiro4989/setup-nim-action/commit/4ee280f29977ef6b472a3c3ad8726354235633de#diff-49f374184f7542706ae947de9d44718eL58

The crash was solved when I set `CHOOSENIM_NO_ANALYTICS`.
