### ISSUE TITLE
Add noColor to choosenim

### ISSUE THREAD

**Issue by juancarlospaco** [jiro4989/setup-nim-action#32]
Add `--noColor -y` to `choosenim` please:
https://github.com/jiro4989/setup-nim-action/blob/927145adf8b0bc94d407e85f6bb526e05ee55208/src/installer.ts#L60

**Comment by jiro4989** [comment]
@juancarlospaco 
I added new input parameters.
https://github.com/jiro4989/setup-nim-action/runs/1531016165?check_suite_focus=true

[action.yml](https://github.com/jiro4989/setup-nim-action/blob/master/action.yml)

**Comment by juancarlospaco** [comment]
Thanks, the logs can look better now. :+1:
