### ISSUE TITLE
setup-nim-action throws error in installer.js line 98

### ISSUE THREAD

**Issue by floooh** [jiro4989/setup-nim-action#331]
## Describe the bug

At some point between 30-Mar and 31-Mar Nim installation via setup-nim-action@v1 started failing at least on Ubuntu and macOS (haven't checked Windows so far).

## To Reproduce

1. go to: https://github.com/floooh/sokol/actions/runs/4576969012/jobs/8081937470
2. See error: ```Error: Error: Command failed: bash init.sh -y`` (more details below)
3. ...same for macos: https://github.com/floooh/sokol/actions/runs/4576969012/jobs/8081937577

## Screenshots or Logs

```
Run jiro4989/setup-nim-action@v1
Error: Error: Command failed: bash init.sh -y

/Users/runner/work/_actions/jiro4989/setup-nim-action/v1/lib/installer.js:98
                throw err;
                ^

Error: Command failed: bash init.sh -y

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:1[6](https://github.com/floooh/sokol/actions/runs/4576969012/jobs/8081937577#step:2:7))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'bash init.sh -y'
}
```

## Environment (please complete the following information)

- OS: ubuntu-latest, macos-latest

**Comment by metagn** [comment]
Experiencing same issue

**Comment by jiro4989** [comment]
Error didn't happen with [scheduled jobs](https://github.com/jiro4989/setup-nim-action/actions/runs/4580512305). Does the error still occur now?

**Comment by jiro4989** [comment]
And, please add `repo-token` parameters, and re-run your CI.

```yaml
  - uses: jiro4989/setup-nim-action@v1
    with:
      nim-version: '1.6.0' # default is 'stable'
      repo-token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by floooh** [comment]
The problem appears to have fixed itself. Today's GH actions were all working without changes.

I also had separate random issues with network connections on GH Actions in the last two days, but those looked different and were not as consistently reproducible.

I'm still going to add the repo-token item nonetheless.

Thanks for your time :)
