### ISSUE TITLE
[DOCS] Convert issue templates to issue forms

### ISSUE THREAD

**Issue by Panquesito7** [jiro4989/setup-nim-action#353]
## Is your feature request related to a problem? Please describe

Converting the issue templates to issue forms will give both the repository maintainers and issue creators the to create better issues. You can use checkboxes, required fields, use Markdown, and much more.

## Describe the solution you'd like

Convert issue templates (`.md`) to issue forms (`.yml`).

## Describe alternatives you've considered

Improve the current Markdown templates.

## Additional context

None.

**Comment by jiro4989** [comment]
@Panquesito7 Thank you. I changed to issue form.
It's still in beta, but it's useful.
