### ISSUE TITLE
add doc comment regarding how to pick nim versions

### ISSUE THREAD

**Issue by timotheecour** [jiro4989/setup-nim-action#38]
as shown in https://github.com/nim-lang/fusion/pull/67, we should pick latest of each branch, so 1.2.0 is probably not what users would want to test (instead, 1.2.8 currently)

is there a way to test for latest stable for 1.2.x branch? that would be the ideal to avoid having to change up a new release

**Comment by jiro4989** [comment]
> is there a way to test for latest stable for 1.2.x branch?

There is not that function.

**Comment by timotheecour** [comment]
see https://github.com/nim-lang/fusion/pull/70#issuecomment-755142942

alaviss/setup-nim@0.1.1 allows using `branch: [version-1-0, version-1-2, version-1-4, devel]` which avoids this problem

**Comment by jiro4989** [comment]
@timotheecour 
Supported `1.n.x` and `1.x` version format.
https://github.com/jiro4989/setup-nim-action#setup-a-latest-patch-version-nim
