### ISSUE TITLE
Error: Unable to process command set-env

### ISSUE THREAD

**Issue by juancarlospaco** [jiro4989/setup-nim-action#40]
I started to see these:

```
Run jiro4989/setup-nim-action@v1.0.2
  with:
    nim-version: 1.4.2
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.1/x64

Error: Unable to process command '::set-env 
name=PATH,::/home/runner/.nimble/bin:/opt/hostedtoolcache/Python/3.9.1/x64/bin:/opt/hostedtoolcache/Python/3.9.1/x64:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' successfully.

Error: The `set-env` command is disabled. 
For more information see: 
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
```

- https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands

I think that it tries to set and env var, but GitHub deprecated that, the GitHub Action aborts now (used to continue before).

**Comment by jiro4989** [comment]
@juancarlospaco 

> Run jiro4989/setup-nim-action@v1.0.2

Please use `jiro4989/setup-nim-action@v1`.
`v1.0.2` is too old.

**Comment by juancarlospaco** [comment]
Still the same error https://github.com/juancarlospaco/faster-than-requests/commit/ab50c5b6bf2e9c06933e546ec9ee9d3fc56d32a4

**Comment by jiro4989** [comment]
> Error: Unable to process command '::set-env 
name=PATH,::/home/runner/.nimble/bin:/opt/hostedtoolcache/Python/3.9.1/x64/bin:/opt/hostedtoolcache/Python/3.9.1/x64:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' successfully.

I think that this error was solved.

- v1.0.2 https://github.com/juancarlospaco/faster-than-requests/actions/runs/552622274
- v1.3 https://github.com/juancarlospaco/faster-than-requests/actions/runs/553285444
