### ISSUE TITLE
SSL error on Windows

### ISSUE THREAD

**Issue by bovine3dom** [jiro4989/setup-nim-action#41]
It looks like `choosenim` doesn't come with the certificates it needs.

```
  Verifying dependencies for tridactyl_native@
    Reading official package list
    Prompt: No local packages.json found, download it from internet? -> [forced yes]
Downloading Official package list
     Trying https://github.com/nim-lang/packages/raw/master/packages.json
   Warning: Could not download: No SSL/TLS CA certificates found.
     Trying https://irclogs.nim-lang.org/packages.json
     Trying https://nim-lang.org/nimble/packages.json
     Error: Refresh failed
        ... Could not download: No SSL/TLS CA certificates found.
Error: Process completed with exit code 1.
```

https://github.com/tridactyl/native_messenger/runs/1998216729?check_suite_focus=true

It was a pretty easy fix:

https://github.com/tridactyl/native_messenger/pull/41/files

---

Feel free to tell me to report this to `choosenim` instead : )

**Comment by jiro4989** [comment]
Thank you.
I reported this problem to `choosenim`.

**Comment by jiro4989** [comment]
@bovine3dom I fixed this problem.

**Comment by bovine3dom** [comment]
Thanks, and thanks for letting me know!
