### ISSUE TITLE
[Feature]: Atlas support.

### ISSUE THREAD

**Issue by treeform** [jiro4989/setup-nim-action#432]
### Is your feature request related to a problem? Please describe

Araq is working on a dependency tool:
*  https://github.com/nim-lang/atlas 
* https://forum.nim-lang.org/t/9748
It would be nice for the tool to become more popular.

**Comment by jiro4989** [comment]
hmm. Will we be able to use `atlas` over time ?

> Upcoming Nim version 2.0 will ship with `atlas` .

Ref: https://github.com/nim-lang/atlas?tab=readme-ov-file#installation
