### ISSUE TITLE
Actions failed

### ISSUE THREAD

**Issue by fox0430** [jiro4989/setup-nim-action#59]
Hello, I noticed today that the CI that succeeded last time fails.

```
Run jiro4989/setup-nim-action@v1
  with:
    nim-version: 1.4.8
    no-color: false
    yes: false
  env:
    NIM_VERSION: 1.4.8
Error: Error: Command failed: sh init.sh -y
init.sh: 90: SHELL: parameter not set
/home/runner/work/_actions/jiro4989/setup-nim-action/v1/lib/installer.js:94
Error: Command failed: sh init.sh -y
init.sh: 90: SHELL: parameter not set
    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'sh init.sh -y'
}
```

https://github.com/fox0430/moe/runs/3781397970

**Comment by jiro4989** [comment]
hmm. This errors occurred in this scheduled tests.

https://github.com/jiro4989/setup-nim-action/runs/3779293117?check_suite_focus=true#step:3:14

**Comment by jiro4989** [comment]
hmm.

`SHELL` environment variables might be removed from GitHub Actions runner.

https://github.com/jiro4989/setup-nim-action/pull/60/checks?check_run_id=3781525856

**Comment by jiro4989** [comment]
I will try appending `SHELL` environment variables when calls `exec` function.

https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by jiro4989** [comment]
@fox0430 I fixed this problem. Please retry your CI in your repository.

**Comment by fox0430** [comment]
@jiro4989 
No problem. Thank you!
